"""Add BookingLock

Revision ID: e3a4b5c6d7e8
Revises: bcb6072179c3
Create Date: 2026-04-26 12:50:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from datetime import datetime


# revision identifiers, used by Alembic.
revision: str = 'e3a4b5c6d7e8'
down_revision: Union[str, None] = 'bcb6072179c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    booking_locks_table = op.create_table('booking_locks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_locked_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_locks_id'), 'booking_locks', ['id'], unique=False)

    # Insert initial row to guarantee get_or_create race conditions are avoided
    op.bulk_insert(booking_locks_table, [
        {'id': 1, 'last_locked_at': datetime.utcnow()}
    ])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_booking_locks_id'), table_name='booking_locks')
    op.drop_table('booking_locks')
    # ### end Alembic commands ###
